# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('megapotek', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataobat',
            old_name='expired',
            new_name='timestamp',
        ),
    ]
